### ISSUE TITLE
TEAM7 - vuln 1 issue

### ISSUE THREAD

**Issue by yjss27** [Philip-sung/SoftwareSecurityCTF#12]
-----BEGIN PGP MESSAGE-----
Version: GnuPG v1

hQGMA6QYfVcr6MtpAQv+PL8JMIf7HDid6JtS+ZE7VW+8ofNRM7DeuC6rzA0f+urk
jzhvAPwJO39sJ5EeItmuQs8bXLYUdfliadkVlSQNu+yQZJJV/h9nheKbWvi21erA
VUOGsnipwnzJFYDu/qC7mWyHFpn3OIHU6ITIG9jRw6zMuh5hA0lSTjzQP9eBdzGf
KjsVpIiLgA3QDkbqUJKz8Gfi+6wN47BPG4RDhXgbq+/BLoL4u2GydFl35up3xMl4
wGlGjD8Lf9uZ2rg6FoN2n5oL8xoh5BzVeH2CeYoO/eJOcR3iLDzvlc089cpxLz6x
F5Fd7Qhzu+soV1IhNk35+qVc/iusKGX8n27AvaNEDNdjWpgWd25C5II7BlJ/nO2q
RV1a712vboCaZX99s8SwBURWAKyVk4kM2H1hV8fyENHxin5sn4QwhPVV4F0i/6UC
VTIge2WjT7Eo7GO3CRePBoUosao85xgvnf8vBpV+6O+gqE11+eex4ckBqXwnXCJN
XwpU5PJ2JMRzoJ26HrmPhQGMA7MoJ8VxJKKQAQv/f5P/FsbolvTQXaAWw+I1I6z1
3Chuo1gelUY9on8M4jsPVYcb0fyMUb5EW8zxoxRY2y/diIrRq3t/axhgTi4uP2gA
17baPMTh5AC8k7im4yruQEtjl0210P20zGPD19Wl+zRs/6imI4SLj4YMXEhzgYM1
HfBepAHeVGqq3g7vNVZSz+pksKgFqMZ+uShHjlTxqRwGoGGOETW82d6dFYD6EVcH
y765tjh0AgQAAZu/pY07w7Z4YdfS9P3p5pNl9o5r/br8OZgqmKXrDQ4EGch3zEn9
DIxaTQGB4bnp8gN/tQjPpb+94aE8Ie0y/CiMLNcosrVV6xgo/8ZVrJ5bfGyqkhPB
23vnthI2qc2GkxwrmItYHFrKM3qTaKCxqfbt5TtPn5zhiOiHkHSbdKMolk5GC5Kv
nK42oufdu9yHP2KN2zrg930oYXWKWj3Ckycjmm3J2JjtdpUDxkfP71k0yPYQs4rh
AiPL+71f4gdQoJBIRshtIzV2OPKdgmCCSYPo+GsIhQGMA01WpxaStsnBAQwAlSRi
pK9Hhfm63jDfiiT4uVgPzhf+5OaKOS9bemMIpKvYelB7e9S2Q6rGRAVJAk81z4G7
9/4kiLJBW4LJsCG8c5wM8v0vWcMGcfZljtTckElVrRJvu4B7epmsvW+748mIraKy
r+hvh2xITAJt/P+qMWhF6rn7YO90DUIlDj7oGZwhTstvYIrnEcMh0EyKa5Orh7eJ
JkLPT3SlnCVgog0EvfLy6ZkHvNw+V/vzpVYpYyvOuxNuCPIEIBQEHxuxrYrnWJSt
PV9H+vthhL2rrg2XePrSf+S+EMcujzqewsXrFF3utkK8VUsCklLXoQbuDc7pjm1G
LRvFDbu1a7JCeiILfeURWMFZGHH6f+7mcKknkTMJZeNfSpSgIvaRl4CWaubWbtjJ
JvW48UFglBd2V4R/E2kdGA/qqhSRE9Q7yCzU4k0Spfhim0s+M6KjXFgrr3xE9yW6
cJ1H9QcYnmKGoF+gsuzaljZ0GKcutyx9JkJQRT9KcAQxbvdUV/aApzHvLZFQ0sCa
AaghrwyfN6TEzvfLWk37557fOsXeO+TAi93AGprCMKtCZzK1onBsJN4pJtY0E4iL
S4Z9lcI3fV0QOCf+kDP4UFaaFp6JqJcc3/AnsGeIK3whKajKdAxSuUTH7ioBnngm
Tvvs9S4zL2dsvsfSuEFKJvHq7HU47Iw8C8xm7C2heQoN1eZdIn1OqLhl72YV0eAw
nnp5grlW2fcdaYslXMRsiyL1bJUBm+02NUo3cj5vJHNrOFaVS1Cdbf5VkpQYmQZp
iJ6AMHw62jAHot7m9qH7JYH/hylNs1IAmzrOqpYK2LhwoPPzhubNchaESqqbwqzd
f913gmC1yydkUAADnXF7N5lqKm2k5sGEmCfyHB+Tf/MXJoRBS9pJZYsHCCLxeERW
E8G/0ZyoqVXbKnAEmfGjiNZumuEYQA9CjPfMV5/cNo3Ct/m+rEf+ZmIXNU2LeIJS
4l7m2Dp8odzLDQ==
=Zz9d
-----END PGP MESSAGE-----

**Comment by Seok345667** [comment]
I think this vulnerability is out of condition. P
lease find a vulnerability that can be manipulated with the input of the web.
